install python by pyenv

diff --git a/script/installer/pyenv b/script/installer/pyenv
--- a/script/installer/pyenv
+++ b/script/installer/pyenv
@@ -1,3 +1,15 @@
 #!/bin/bash
 
 git clone https://github.com/pyenv/pyenv.git "$HOME/.pyenv"
+
+export PYENV_ROOT="$HOME/.pyenv"
+export PATH="$PYENV_ROOT/bin"
+eval "$(pyenv init -)"
+
+PYTHON_VERSION=$(pyenv install -l | grep '^ *3.[0-9].[0-9]' | sort | tail -n 1)
+pyenv install $PYTHON_VERSION
+
+cd "$(mktemp -d)" || { echo "Failed to move to tempdir"; exit 1; }
+pyenv local $PYTHON_VERSION
+pip install --upgrade pip
+pip install numpy scipy ipython jupyter jupyterlab
